prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'capi-providers'
        # 15s is a bit often for production but helps to get metrics quicker for development.
        scrape_interval: 15s
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_labelpresent_cluster_x_k8s_io_provider]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: metrics
          - source_labels: [__meta_kubernetes_pod_label_cluster_x_k8s_io_provider]
            action: replace
            target_label: provider
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod